###################################################################################################
# This file is only used as a source of truth for the settings that are necessary for the examples.
###################################################################################################

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper-kafka-example
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka1:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka1-example
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka2:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka2-example
    depends_on:
      - zookeeper
    ports:
      - '9093:9093'
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop-example
    restart: always
    ports:
      - '9000:9000'
    environment:
      KAFKA_BROKERCONNECT: 'kafka1:29092,kafka2:29093'
    depends_on:
      - kafka1
      - kafka2

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-example
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  fluent-bit:
    image: fluent/fluent-bit:2.2.2
    container_name: fluent-bit-collector
    ports:
      - '5170:5170/udp'
    volumes:
      - ./90-custom-transport-compliance/config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  nats:
    image: nats:latest
    container_name: nats-example
    restart: always
    ports:
      - '4222:4222' # Client port
      - '8222:8222' # HTTP management port

  redis:
    image: 'redis:alpine'
    container_name: redis-example
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
