version: '3.8'

services:
  nats:
    image: nats:2.10-alpine
    container_name: nats-basic
    ports:
      - "4222:4222"  # NATS client port
      - "8222:8222"  # NATS monitoring port
    command: nats-server --jetstream --http_port 8222
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped 