# Este es un archivo de configuración mínimo para Verdaccio.
# Permite a cualquier usuario publicar e instalar paquetes sin autenticación.
# Ideal para pruebas locales.

# Ruta donde se guardarán los paquetes dentro del contenedor.
# Coincide con el volumen definido en docker-compose.yaml.
storage: /verdaccio/storage

# Ruta para los plugins, si los hubiera.
plugins: /verdaccio/plugins

web:
  title: Verdaccio Local Registry (For Testing)

# Permisos de los paquetes.
packages:
  '@*/*':
    access: $all
    publish: $all
    unpublish: $all
  '**':
    access: $all
    publish: $all
    unpublish: $all
