version: '3.8'

services:
  nats-server:
    image: nats:2.9.25-alpine
    ports:
      - "4222:4222"
      - "8222:8222" # Expose monitor port

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api-gateway:
    build:
      context: ../..
      dockerfile: examples/24-full-stack-nats/Dockerfile
      args:
        - NODE_AUTH_TOKEN=${NODE_AUTH_TOKEN}
    command: node ./dist/api-gateway/index.js
    ports:
      - "3000:3000"
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - REDIS_URL=redis://redis:6379
    depends_on:
      - nats-server
      - redis

  sales-service:
    build:
      context: ../..
      dockerfile: examples/24-full-stack-nats/Dockerfile
      args:
        - NODE_AUTH_TOKEN=${NODE_AUTH_TOKEN}
    command: node ./dist/sales-service/index.js
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - REDIS_URL=redis://redis:6379
    depends_on:
      - nats-server
      - redis

  dispatch-service:
    build:
      context: ../..
      dockerfile: examples/24-full-stack-nats/Dockerfile
      args:
        - NODE_AUTH_TOKEN=${NODE_AUTH_TOKEN}
    command: node ./dist/dispatch-service/index.js
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - REDIS_URL=redis://redis:6379
    depends_on:
      - nats-server
      - redis 